### ISSUE TITLE
dmg package window bugs

### ISSUE THREAD

**Issue by omarcostahamido** [sauraen/HQStreamer2#2]
on the readme it says:
"You may install whichever versions (VST3, Standalone, AU, AUv3) just by dragging the packages to the target folders following the arrows."
At least on Mac OS Catalina those arrows don't appear.

Also, the VST shortcut (alias) doesn't work.

Also (x2), and this might be Catalina specific, I cannot drag. I need to copy, open the folder, and paste (giving permission in the popup window)

OCH

**Comment by sauraen** [comment]
I've made a number of changes to the DMG and the install process, this should be fixed now. Please try the DMG again and feel free to reopen this issue if it doesn't work seamlessly on your machine.
